<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuerto [
   <!ELEMENT aeropuerto (nombre, vuelos, fecha)>
     <!ELEMENT nombre (#PCDATA)>
     <!ELEMENT vuelos (vuelo+)>
            <!ELEMENT vuelo (diario?, origen, destino, horasalida, horallegada)>
                        <!ATTLIST vuelo codigo ID #REQUIRED>
                        <!ATTLIST vuelo estado (C | E | R) "E">
                   <!ELEMENT diario EMPTY>
                   <!ELEMENT origen (#PCDATA)>
                   <!ELEMENT destino (#PCDATA)>
                   <!ELEMENT horasalida (#PCDATA)>
                   <!ELEMENT horallegada (#PCDATA)>
     <!ELEMENT fecha (#PCDATA)>
]>
<aeropuerto>
   <nombre>JFK</nombre>
   <vuelos>
      <vuelo codigo="V22" estado="R">
         <diario />
         <origen>New York</origen>
         <destino>Chicago</destino>
         <horasalida>9:30</horasalida>
         <horallegada>11:30</horallegada>
      </vuelo>
      <vuelo codigo="V23" estado="C">
         <origen>New York</origen>
         <destino>Miami</destino>
         <horasalida>10:15</horasalida>
         <horallegada>11:15</horallegada>
      </vuelo>
   </vuelos>
   <fecha>20/12/2013</fecha>
</aeropuerto>
