<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD de departamentos -->
<!DOCTYPE departamentos [
<!ELEMENT departamentos (departamento+)>
<!ELEMENT departamento (nomdept, responsable, personas)>
<!ELEMENT nomdept (#PCDATA)>
<!ELEMENT responsable (nombre, apellidos, email, extensión)>
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre, apellidos, email, extension)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT extension (#PCDATA)>
                        ]>

<departamentos>
    <departamento>
        <nomdept>Dpto1234</nomdept>
        <responsable></responsable>
        <personas></personas>
    </departamento>
    <responsable>
        <nombre>Marichu</nombre>
        <apellidos>Papitos</apellidos>
        <email>marichupapitos@aventurera.es</email>
        <extension>942</extension>
    <personas>
        <persona>
            <nombre>Jaime</nombre>
            <apellidos>Tepatas</apellidos>
            <email></email>
            <extension></extension>
        </persona>
    </personas>    
    </responsable>
</departamentos>