<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas [
 <!ELEMENT factura (datosemisor, datoscliente, detallefactura)>
    <!ATTLIST numfactura ID #REQUIRED>
    <!ATTLIST fechafactura CDATA #REQUIRED>
<!ELEMENT datosemisor(emisornombre, emisorcif, emisortfno)>
<!ELEMENT emisornombre (#PCDATA)>
<!ELEMENT emisorcif (#PCDATA)>
<!ELEMENT emisortfno(#PCDATA)>
<!ELEMENT datoscliente(clientenombre, clientecif, clientetfno)>
<!ELEMENT clientenombre (#PCDATA)>
<!ELEMENT clientecif (#PCDATA)>
<!ELEMENT clientetfno (#PCDATA)>
<!ELEMENT detallefactura (codarticulo, tipo, descripc, cant,ofer,pvp)>
<!ELEMENT codarticulo (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT descripc (#PCDATA)>
<!ELEMENT cant (#PCDATA)>
<!ELEMENT ofer (#PCDATA)>
<!ELEMENT pvp (#PCDATA)>
                                 ]>

<facturas>
  <factura>
    <datosemisor></datosemisor>
    <datoscliente></datoscliente>
    <detallefactura numfactura ="01234" fechafactura="13/08/2019"
     tipo="num">
                            <item>Libro</item>
                            <item>DVD</item>
                            <item>Varios</item>
                      
    </detallefactura>

    <datosemisor>
        <emisornombre></emisornombre>
        <emisorcif></emisorcif>
        <emisortfno></emisortfno>
    </datosemisor>

    <datoscliente>
        <clientenombre></clientenombre>
        <clientecif></clientecif>
        <clientetfno></clientetfno>
    </datoscliente> 

  </factura>

</factura>
